# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

SoftMax <- function(x) {
    .Call('_transformer_SoftMax', PACKAGE = 'transformer', x)
}

attention <- function(Q, K, V) {
    .Call('_transformer_attention', PACKAGE = 'transformer', Q, K, V)
}

feed_forward <- function(x, dff, d_model) {
    .Call('_transformer_feed_forward', PACKAGE = 'transformer', x, dff, d_model)
}

fill_mat_rnorm <- function(mat) {
    invisible(.Call('_transformer_fill_mat_rnorm', PACKAGE = 'transformer', mat))
}

fill_mat_row <- function(nb_Row, row_Vec) {
    .Call('_transformer_fill_mat_row', PACKAGE = 'transformer', nb_Row, row_Vec)
}

insert_sub_mat <- function(mat, sub_Mat, col_Index) {
    invisible(.Call('_transformer_insert_sub_mat', PACKAGE = 'transformer', mat, sub_Mat, col_Index))
}

layer_norm <- function(x, epsilon) {
    .Call('_transformer_layer_norm', PACKAGE = 'transformer', x, epsilon)
}

mat_mult <- function(mat1, mat2) {
    .Call('_transformer_mat_mult', PACKAGE = 'transformer', mat1, mat2)
}

mat_sum <- function(mat1, mat2) {
    .Call('_transformer_mat_sum', PACKAGE = 'transformer', mat1, mat2)
}

multi_head <- function(Q, K, V, d_model, num_heads) {
    .Call('_transformer_multi_head', PACKAGE = 'transformer', Q, K, V, d_model, num_heads)
}

pmax_mat <- function(mat) {
    .Call('_transformer_pmax_mat', PACKAGE = 'transformer', mat)
}

row_max <- function(mat) {
    .Call('_transformer_row_max', PACKAGE = 'transformer', mat)
}

row_means <- function(mat) {
    .Call('_transformer_row_means', PACKAGE = 'transformer', mat)
}

row_vars <- function(mat) {
    .Call('_transformer_row_vars', PACKAGE = 'transformer', mat)
}

sub_mat <- function(mat, col_Index) {
    .Call('_transformer_sub_mat', PACKAGE = 'transformer', mat, col_Index)
}

